services:
  gamelibrary:
    image: ${DOCKER_REGISTRY-}gamelibrary
    build:
      context: .
      dockerfile: GameLibrary/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - "${SECRETS_PATH}/usersecrets:/home/app/.microsoft/usersecrets:ro"
      - "${HTTPS_PATH}/https:/home/app/.aspnet/https:ro"
