blank_issues_enabled: false
contact_links:
  - name: "🐞 Report a Bug"
    url: "/issues/new?template=BUG-REPORT.yml"
    about: "Let us know about a bug or issue."

  - name: "✨ Request a Feature"
    url: "/issues/new?template=FEATURE-REQUEST.yml"
    about: "Suggest a new feature or improvement."
